// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package main

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (School) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*School) UnmarshalJSON([]byte) error        { return nil }
func (School) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*School) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_School *School

func (Student) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Student) UnmarshalJSON([]byte) error        { return nil }
func (Student) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Student) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Student *Student
